version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: enterprise_db
    restart: always
    environment:
      POSTGRES_DB: enterprise_task_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mehedi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: enterprise_backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgrespassword@postgres:5432/enterprise_task_db
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: enterprise_frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  postgres_data:
